bstr: fix compile warning strict-prototypes
Tested on Fedora 37 with clang 15.

/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I..   -O2 -I.. -I../htp -D_GNU_SOURCE -g -Wall -Wextra -std=gnu99 -pedantic -Wextra -Wno-missing-field-initializers -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wno-unused-parameter -Wall -Werror -Wunreachable-code -Wno-unused-parameter -Wno-unused-function -O2 -Wstrict-overflow=1 -fstack-protector -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fPIC -MT bstr_builder.lo -MD -MP -MF .deps/bstr_builder.Tpo -c -o bstr_builder.lo bstr_builder.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -O2 -I.. -I../htp -D_GNU_SOURCE -g -Wall -Wextra -std=gnu99 -pedantic -Wextra -Wno-missing-field-initializers -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wno-unused-parameter -Wall -Werror -Wunreachable-code -Wno-unused-parameter -Wno-unused-function -O2 -Wstrict-overflow=1 -fstack-protector -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fPIC -MT bstr_builder.lo -MD -MP -MF .deps/bstr_builder.Tpo -c bstr_builder.c  -fPIC -DPIC -o .libs/bstr_builder.o
bstr_builder.c:70:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
bstr_builder_t *bstr_builder_create() {
                                   ^
                                    void
1 error generated.